### ISSUE TITLE
King Zephiel's animation w/Eckesachs

### ISSUE THREAD

**Issue by laqieer** [Klokinator/FE-Repo#35]
https://github.com/Klokinator/FE-Repo/tree/69872e8a6df143b42f2fe4b7ac2e2974db4d6b29/Battle%20Animations/Infantry%20-%20Knights%2C%20Generals%2C%20Armors/%5BZephiel-Base%5D%20%5BM%5D%20King%20Zephiel%20Vanilla%20%2BWeapons
![](https://github.com/Klokinator/FE-Repo/raw/69872e8a6df143b42f2fe4b7ac2e2974db4d6b29/Battle%20Animations/Infantry%20-%20Knights%2C%20Generals%2C%20Armors/%5BZephiel-Base%5D%20%5BM%5D%20King%20Zephiel%20Vanilla%20%2BWeapons/1.%20Sword%20(Eckesachs%20FE6)/Sword_029.png)
The direction of the sword during rotation is incorrect.
Compared to: https://youtu.be/HaO72ELpA5c

**Comment by anishyellaturu** [comment]
This is because the animating of the sword rotation is a hardcoded process, which does not display properly with the gif export. The animation displays correctly in-game.

**Comment by Klokinator** [comment]
Gif exports don't always look correct. Import into the game first to check before reporting an issue, as the animation looks correct ingame.
