### ISSUE TITLE
Mortal Savant error in the files

### ISSUE THREAD

**Issue by Daniel-ags** [Klokinator/FE-Repo#72]
![image](https://github.com/Klokinator/FE-Repo/assets/53279612/740fe410-7ebf-4c95-8831-5a95c59ffacd)

(Probably) Something in the dmp file is missing a word or 2

The error is specifically happening with the Magic animation, with both the male and female sprites.

**Comment by Klokinator** [comment]
@Daniel-ags Did you try inserting the other insertable files? You can insert the .dmp, the file without an extension, or the text file with/without comments. Sometimes only one of those will work.

**Comment by Daniel-ags** [comment]
Thank You! I tried with the .txt and it worked!

Now, before u close this issue. Can i get someone that does the arts to help me with something?

I've been trying to create some new sprites for weapons, but everytime i go to import to the rom, FEBuilder gives me a prompt to correct the colors and it always ends up different from what i did. Can someone halp plz?!?!

**Comment by Klokinator** [comment]
You can ask questions about that stuff on the Repo discord. 

https://discord.gg/2jRGfDxvTZ
