### ISSUE TITLE
Broken anime bin file

### ISSUE THREAD

**Issue by minghu6** [Klokinator/FE-Repo#77]
In the `unarmed` anime folder which belongs to [[Warrior-Reskin] [F] FEGirls Thin](https://github.com/Klokinator/FE-Repo/tree/main/Battle%20Animations/Infantry%20-%20(Axe)%20Fighters%20and%20Warriors/%5BWarrior-Reskin%5D%20%5BF%5D%20FEGirls%20Thin).

The `Unarmed.bin` just show an empty scene, is different from `Unarmed.gif` and `Unarmed*.txt` .

**Comment by minghu6** [comment]
After import the `Unarmed.bin` file:
![无标题](https://github.com/Klokinator/FE-Repo/assets/13537217/297208f3-e254-498c-8cf9-dd9786c15cdc)

The `Unarmed.txt` and `Unarmed_without_comment.txt` are ok after imported  (though i'm not sure it‘s’ behaved as author expected)

**Comment by minghu6** [comment]
After import the `Unarmed.bin` file:
![无标题](https://github.com/Klokinator/FE-Repo/assets/13537217/297208f3-e254-498c-8cf9-dd9786c15cdc)

The `Unarmed.txt` and `Unarmed_without_comment.txt` are ok after imported  (though i'm not sure it‘s’ behaved as author expected)

**Comment by Klokinator** [comment]
Okay. Yeah, sometimes one type doesn't work. It's no big deal, just try the other ones. If ALL of them fail, definitely report that.

Thanks for the heads up in any case!
