### ISSUE TITLE
Pics not found. Getting 404 error

### ISSUE THREAD

**Issue by EnvySSB** [Klokinator/FE-Repo#79]
I've started using this repo a few days ago and had no issues. only today have i noticed the pictures for the categorized ones are broken it seems
![Screenshot_58](https://github.com/Klokinator/FE-Repo/assets/169392890/16c98f5a-b9a8-4a90-a08c-65d262e7f162)

**Comment by Klokinator** [comment]
Oh, Jey pushed an update and didn't tell me to update the readme. Le sigh.

**Comment by EnvySSB** [comment]
Ah gotcha! I was gettin kinda sad cuz its such a great place to get some fun stuff, Really appreciate this whole repository

**Comment by Klokinator** [comment]
Should be fixed now. Thanks for the report.
