### ISSUE TITLE
Thief relpalette for matthew URL not working

### ISSUE THREAD

**Issue by EnvySSB** [Klokinator/FE-Repo#80]
![Screenshot_4](https://github.com/Klokinator/FE-Repo/assets/169392890/a276dbbc-0acf-4fe3-94ad-7d9e168a5e4a)
![Screenshot_3](https://github.com/Klokinator/FE-Repo/assets/169392890/cca6ffa9-77d9-462b-9c22-5d398e1d1b11)

Hey there, I just went to DL this thief here and it seems that the URL is not working. Other downloads are working fine, so I don't believe its the website. Was hoping I could get an updated link or something. Thanks!

-If for some reason the screenshots dont work, its the thief matthew repal by Pikmin +knife +bow. Easy to find

**Comment by Klokinator** [comment]
I'm not sure why this link isn't working. It might be an issue with DownGit.

Try looking at the Advanced User section of the repo tutorial.

[https://feuniverse.us/t/github-and-you-maximizing-your-usage-of-the-new-graphics-repository/11815](https://feuniverse.us/t/github-and-you-maximizing-your-usage-of-the-new-graphics-repository/11815)

Use Gitzip to download folders. I've never had an issue with it and it works well!
